(function () {
  'use strict';
  var EN = {
    "Nenhum botão ainda": "No buttons yet",
    "No computador, abra o editor do deck e escolha os apps e sites — eles aparecem aqui na hora.": "On the computer, open the deck editor and pick apps and sites — they show up here instantly.",
    "Conectado": "Connected",
    "Sem conexão com o computador": "No connection to the computer",
    "Reconectando…": "Reconnecting…",
    "Conectando…": "Connecting…",
    "Toque de novo": "Tap again",
    "Os botões mudaram no computador.": "The buttons changed on the computer.",
    "Não funcionou.": "It didn't work.",
    "Sem resposta do computador. Ele está ligado, na mesma rede e com o deck aberto?": "No answer from the computer. Is it on, on the same network, with the deck open?",
    " — o deck segue com a última versão que funcionava.": " — the deck keeps running the last version that worked.",
    "1 aviso": "1 warning",
    "{n} avisos": "{n} warnings",
    "Desconectado": "Disconnected",
    "Desconectado pelo computador": "Disconnected by the computer",
    "Este aparelho foi desconectado em Conectar celular. Para voltar, peça para liberar lá — e abra o app de novo.": "This device was disconnected in Connect phone. To come back, ask to allow it there — then open the app again.",
    "Link inválido": "Invalid link",
    "Link antigo": "Old link",
    "Este link não vale mais. No computador, abra a página do QR code e escaneie de novo com a câmera do celular.": "This link no longer works. On the computer, open the QR code page and scan it again with the phone's camera.",
    "Para usar como app em tela cheia: toque em <b>Compartilhar</b> e depois em <b>Adicionar à Tela de Início</b>.": "To use it as a full-screen app: tap <b>Share</b>, then <b>Add to Home Screen</b>.",
    "Para ter um atalho: menu <b>⋮</b> e depois <b>Adicionar à tela inicial</b>. O botão de tela cheia esconde as barras e deixa deitado.": "For a shortcut: menu <b>⋮</b>, then <b>Add to Home screen</b>. The full-screen button hides the bars and turns it landscape.",
    "Sem link": "No link",
    "Conecte ao computador": "Connect to the computer",
    "No computador, rode o deck e escaneie o QR code com a câmera do celular.": "On the computer, run the deck and scan the QR code with the phone's camera.",
    "Computador fora do alcance": "Computer out of reach",
    "Confira se o computador está ligado, na mesma rede e com o deck aberto. Tentando de novo…": "Check that the computer is on, on the same network, with the deck open. Trying again…",
    "Tela cheia": "Full screen",
    "Fechar dica": "Close tip",
    "Avisos dos botões": "Button warnings",
    "Corrija no editor do computador — o celular atualiza sozinho.": "Fix it in the editor on the computer — the phone updates by itself.",
    "Entendi": "Got it",
    "Cabo USB": "USB cable",
    "Rede do computador": "Computer's network",
    "QR code do link do Deck": "QR code of the Deck link",
    "Salve na tela inicial para abrir como app. <small>iPhone: <b>Compartilhar</b> › <b>Adicionar à Tela de Início</b>. Android: menu <b>⋮</b> › <b>Adicionar à tela inicial</b>.</small>": "Save it to the home screen to open it as an app. <small>iPhone: <b>Share</b> › <b>Add to Home Screen</b>. Android: menu <b>⋮</b> › <b>Add to Home screen</b>.</small>",
    "Celular no <b>mesmo Wi-Fi</b> deste computador. <small>Redes de visitantes e de empresa costumam isolar os aparelhos; se não abrir, use o cabo USB ou o Bluetooth.</small>": "Phone on the <b>same Wi-Fi</b> as this computer. <small>Guest and company networks often isolate devices; if it doesn't open, use the USB cable or Bluetooth.</small>",
    "Abra a <b>câmera</b> do celular, aponte para o código e toque no link.": "Open the phone's <b>camera</b>, point it at the code and tap the link.",
    "No iPhone: <b>Ajustes › Hotspot Pessoal › Permitir que Outros se Conectem</b>. <small>Android: Ajustes › Conexões › Roteador Wi-Fi e Ancoragem › <b>Ancoragem USB</b>{mac}.</small>": "On iPhone: <b>Settings › Personal Hotspot › Allow Others to Join</b>. <small>Android: Settings › Connections › Mobile Hotspot and Tethering › <b>USB tethering</b>{mac}.</small>",
    " (no Mac, só Android 14 ou mais novo)": " (on a Mac, only Android 14 or newer)",
    "Ligue o <b>cabo</b> entre o celular e o computador. Se o celular perguntar <b>\"Confiar neste computador?\"</b>, toque em Confiar.": "Connect the <b>cable</b> between the phone and the computer. If the phone asks <b>\"Trust This Computer?\"</b>, tap Trust.",
    "Quando o computador enxergar o celular, o código aparece aqui sozinho. Escaneie com a câmera e ": "When the computer sees the phone, the code shows up here by itself. Scan it with the camera and ",
    "No iPhone: <b>Ajustes › Hotspot Pessoal</b> ligado, e Bluetooth ligado nos dois aparelhos. <small>Android: Roteador Wi-Fi e Ancoragem › <b>Ancoragem Bluetooth</b>.</small>": "On iPhone: <b>Settings › Personal Hotspot</b> on, and Bluetooth on in both devices. <small>Android: Mobile Hotspot and Tethering › <b>Bluetooth tethering</b>.</small>",
    "Pareie: <b>Ajustes do Sistema › Bluetooth</b> › conecte ao celular.": "Pair: <b>System Settings › Bluetooth</b> › connect to the phone.",
    "Pareie: <b>Configurações › Bluetooth e dispositivos › Adicionar dispositivo</b>.": "Pair: <b>Settings › Bluetooth & devices › Add device</b>.",
    "Pareie o celular nas configurações de Bluetooth do computador.": "Pair the phone in the computer's Bluetooth settings.",
    "Entre na rede do celular: menu <b>Bluetooth</b> da barra › nome do celular › <b>Conectar à Rede</b>. O código aparece aqui quando a conexão subir.": "Join the phone's network: <b>Bluetooth</b> menu in the menu bar › phone's name › <b>Connect to Network</b>. The code shows up here when the connection is up.",
    "Entre na rede do celular: <b>Bluetooth e dispositivos › Dispositivos</b> › ⋯ no celular › <b>Ingressar em rede de área pessoal</b> › Ponto de acesso. O código aparece aqui quando a conexão subir.": "Join the phone's network: <b>Bluetooth & devices › Devices</b> › ⋯ on the phone › <b>Join a personal area network</b> › Access point. The code shows up here when the connection is up.",
    "Conecte-se à rede do celular pelo Bluetooth (no GNOME: Configurações › Bluetooth › celular › Acesso à Internet). O código aparece aqui quando a conexão subir.": "Join the phone's network over Bluetooth (in GNOME: Settings › Bluetooth › phone › Internet access). The code shows up here when the connection is up.",
    "<b>Ajustes do Sistema › Geral › Compartilhamento › Compartilhamento de Internet</b> ⓘ: compartilhar a conexão <b>Wi-Fi</b> com computadores que usam <b>Bluetooth PAN</b>. Depois ligue o Compartilhamento de Internet.": "<b>System Settings › General › Sharing › Internet Sharing</b> ⓘ: share the <b>Wi-Fi</b> connection with computers using <b>Bluetooth PAN</b>. Then turn Internet Sharing on.",
    "No celular: <b>Ajustes › Bluetooth</b> › toque no nome do Mac e aceite o pareamento. <small>Android: depois do pareamento, ⚙ ao lado do Mac › <b>Acesso à Internet</b>.</small>": "On the phone: <b>Settings › Bluetooth</b> › tap the Mac's name and accept the pairing. <small>Android: after pairing, ⚙ next to the Mac › <b>Internet access</b>.</small>",
    "O código aparece aqui quando a rede subir (o endereço é sempre 192.168.2.1, então não muda). Escaneie e ": "The code shows up here when the network is up (the address is always 192.168.2.1, so it never changes). Scan it and ",
    "<b>Configurações › Rede e Internet › Ponto de acesso móvel</b> › ligar.": "<b>Settings › Network & internet › Mobile hotspot</b> › turn on.",
    "No celular, entre no Wi-Fi do computador com o nome e a senha mostrados ali.": "On the phone, join the computer's Wi-Fi with the name and password shown there.",
    "O código aparece aqui quando a rede subir (endereço 192.168.137.1, que não muda). Escaneie e ": "The code shows up here when the network is up (address 192.168.137.1, which never changes). Scan it and ",
    "Configurações › Wi-Fi › menu <b>⋮</b> › <b>Ligar ponto de acesso Wi-Fi</b>.": "Settings › Wi-Fi › menu <b>⋮</b> › <b>Turn on Wi-Fi hotspot</b>.",
    "No celular, entre no Wi-Fi do computador com a senha mostrada ali.": "On the phone, join the computer's Wi-Fi with the password shown there.",
    "O código aparece aqui quando a rede subir. Escaneie e ": "The code shows up here when the network is up. Scan it and ",
    "Funciona com qualquer celular na mesma rede. É a opção mais simples.": "Works with any phone on the same network. The simplest option.",
    "Zero atraso, carrega o celular e não depende de roteador. Enquanto o cabo estiver ligado, o computador pode passar a usar a internet do celular.": "Zero lag, charges the phone and doesn't depend on a router. While the cable is connected, the computer may start using the phone's internet.",
    "Sem cabo e sem roteador. Mais lento que Wi-Fi e cabo, mas sobra para apertar botões.": "No cable and no router. Slower than Wi-Fi and cable, but more than enough for pressing buttons.",
    "Para quando não há Wi-Fi nenhum por perto, ou o plano do celular não tem hotspot. A internet do celular passa a vir pelo computador.": "For when there's no Wi-Fi around, or the phone plan has no hotspot. The phone's internet then comes through the computer.",
    "Esperando o celular pelo cabo…": "Waiting for the phone over the cable…",
    "Esperando a conexão por Bluetooth…": "Waiting for the Bluetooth connection…",
    "Esperando a rede do computador subir…": "Waiting for the computer's network to come up…",
    "Não achei o endereço deste computador na rede. Ele está no Wi-Fi?": "Couldn't find this computer's address on the network. Is it on Wi-Fi?",
    "Forma de conexão": "Connection method",
    "Gerando o código…": "Generating the code…",
    "Tipo de endereço": "Address type",
    "Pelo nome": "By name",
    "Pelo IP": "By IP",
    "Copiar link": "Copy link",
    "Esperando o celular abrir o link…": "Waiting for the phone to open the link…",
    "Gerar link novo (desconecta todos)": "Generate a new link (disconnects everyone)",
    "Abriu com a <b>tela preta</b>? Feche o app no celular (deslize para cima) e abra de novo. Se continuar, escaneie o QR code de novo.": "Opened with a <b>black screen</b>? Close the app on the phone (swipe up) and open it again. If it persists, scan the QR code again.",
    "O nome ({n}) continua valendo mesmo se o IP mudar — o melhor para iPhone. Android não abre por nome: use \"Pelo IP\".": "The name ({n}) keeps working even if the IP changes — best for iPhone. Android doesn't open by name: use \"By IP\".",
    "Abre em qualquer celular. Se o IP do computador mudar, é preciso escanear de novo": "Opens on any phone. If the computer's IP changes, you need to scan again",
    " — por isso o nome é melhor no iPhone.": " — that's why the name is better on iPhone.",
    "Celular visto em: ": "Phone seen on: ",
    "desconectado": "disconnected",
    "conectado agora": "connected now",
    "visto há {t}": "seen {t} ago",
    " dias": " days",
    "Permitir de novo": "Allow again",
    "Desconectar": "Disconnect",
    "{n} aparelhos conectados": "{n} devices connected",
    "{a} conectado": "{a} connected",
    "Pronto — pode fechar esta janela.": "Done — you can close this window.",
    "Nenhum celular conectado agora": "No phone connected right now",
    "Abra o Deck no celular. Se ele não achar o computador, escaneie o código de novo.": "Open Deck on the phone. If it can't find the computer, scan the code again.",
    "Problema no config.json: ": "Problem in config.json: ",
    "Não deu.": "It didn't work.",
    "Tem certeza? Todos os celulares vão precisar escanear de novo — clique outra vez": "Are you sure? Every phone will need to scan again — click once more",
    "Não consegui gerar o link novo.": "Couldn't generate the new link.",
    "Selecionado": "Selected",
    "Copiado": "Copied",
    "O deck foi desligado.": "The deck was turned off.",
    "Ligue de novo no computador.": "Start it again on the computer.",
    "a {c}": "to {c}",
    "este computador": "this computer",
    "Escolher os botões →": "Choose the buttons →",
    "Conectar o celular": "Connect the phone",
    "a este computador": "to this computer",
    "Abre um programa": "Opens a program",
    "Abre uma aba no navegador": "Opens a browser tab",
    "Atalho de teclado": "Keyboard shortcut",
    "Aperta teclas, ex.: copiar": "Presses keys, e.g. copy",
    "Texto": "Text",
    "Digita uma frase pronta": "Types a ready-made phrase",
    "Mídia": "Media",
    "Tocar, pausar e pular": "Play, pause and skip",
    "Subir, baixar ou mudo": "Up, down or mute",
    "Microfone": "Microphone",
    "Liga e desliga o mudo": "Mutes and unmutes",
    "Energia": "Power",
    "Desligar, reiniciar, suspender, bloquear": "Shut down, restart, sleep, lock",
    "Ir para página": "Go to page",
    "Troca a página no celular": "Switches the page on the phone",
    "Teclas": "Keys",
    "Atalho": "Shortcut",
    "Comando": "Command",
    "Página": "Page",
    "Sequência": "Sequence",
    "Esperar": "Wait",
    "comando do terminal": "terminal command",
    "atalho do app Atalhos": "Shortcuts app shortcut",
    "sequência de ações": "sequence of actions",
    "espera": "wait",
    "Anterior": "Previous",
    "Tocar/Pausar": "Play/Pause",
    "Próxima": "Next",
    "Subir": "Up",
    "Baixar": "Down",
    "Mudo": "Mute",
    "Desligar": "Shut down",
    "Reiniciar": "Restart",
    "Suspender": "Sleep",
    "Bloquear": "Lock",
    "Seus atalhos mais usados, sempre à mão.": "Your most used shortcuts, always at hand.",
    "Os programas que você mais abre.": "The programs you open most.",
    "Suas abas e sites, com o ícone de cada um.": "Your tabs and sites, each with its icon.",
    "Tocar, pausar e controlar o som.": "Play, pause and control the sound.",
    "Atalhos que aceleram o seu dia.": "Shortcuts that speed up your day.",
    "Suas músicas e players, num toque.": "Your music and players, one tap away.",
    "Conversas e reuniões, sem procurar a aba.": "Chats and meetings, without hunting for the tab.",
    "O que você usa no trabalho.": "What you use at work.",
    "Captura, câmera e transmissão.": "Capture, camera and streaming.",
    "Ferramentas de quem programa.": "Tools for people who code.",
    "Jogos e lançadores.": "Games and launchers.",
    "Suas coisas de casa.": "Your home stuff.",
    "Botão": "Button",
    "Tipo": "Type",
    "Cor": "Color",
    "Salvando…": "Saving…",
    "Salvo": "Saved",
    "Não salvou": "Not saved",
    "Sem conexão": "No connection",
    "O config.json mudou fora do editor — carreguei a versão nova.": "config.json changed outside the editor — the new version was loaded.",
    "Sem conexão com o deck. Ele foi desligado? Ligue de novo no computador — o que você mudar aqui é salvo quando ele voltar.": "No connection to the deck. Was it turned off? Start it again on the computer — what you change here is saved when it's back.",
    "O config.json tem um erro ({e}). Aqui aparece a última versão que funcionava; se você mudar algo no editor, o arquivo é corrigido.": "config.json has an error ({e}). This shows the last version that worked; if you change something in the editor, the file gets fixed.",
    "Clique duas vezes para renomear": "Double-click to rename",
    "Página vazia — adicione um app ou um site.": "Empty page — add an app or a site.",
    "1 botão": "1 button",
    "{n} botões": "{n} buttons",
    "1 espaço livre": "1 free space",
    "{n} espaços livres": "{n} free spaces",
    "página cheia": "page full",
    "Continuação — no celular vira a página “{p}” (tem mais botões do que cabem na grade).": "Continuation — on the phone it becomes page “{p}” (more buttons than fit in the grid).",
    "Em outras páginas": "On other pages",
    "Espaço vazio {n}: adicionar botão": "Empty space {n}: add button",
    " — editar": " — edit",
    "Novo botão": "New button",
    "Configurações": "Settings",
    "Ícone da página": "Page icon",
    "{u} de {c} espaços usados · esta é a página {p} de {t}": "{u} of {c} spaces used · this is page {p} of {t}",
    "Nome da página": "Page name",
    "Ícone": "Icon",
    "É a única página": "It's the only page",
    "Apagar esta página": "Delete this page",
    "Grade": "Grid",
    "({n} botões por página)": "({n} buttons per page)",
    "Tema": "Theme",
    "Preto": "Black",
    "Normal": "Normal",
    "Fundo OLED, bordas e brilho na cor de cada ícone.": "OLED background, borders and glow in each icon's color.",
    "Grafite azulado, mais discreto.": "Bluish graphite, more discreet.",
    "Mostrar QR code": "Show QR code",
    "Idioma": "Language",
    "Automático (idioma do computador)": "Automatic (computer's language)",
    "Este computador": "This computer",
    "Tema (no computador e no celular)": "Theme (on the computer and the phone)",
    "Grade (celular deitado)": "Grid (phone in landscape)",
    "Em pé, as colunas viram linhas. Páginas com mais botões do que a grade viram telas extras.": "In portrait, columns become rows. Pages with more buttons than the grid become extra screens.",
    "Vale para o editor, o celular e o guia. Automático segue o idioma do computador.": "Applies to the editor, the phone and the guide. Automatic follows the computer's language.",
    "Celular": "Phone",
    "Os botões aparecem no celular na hora, sem precisar reconectar.": "Buttons show up on the phone instantly, no need to reconnect.",
    "Página “{p}” · espaço {n}": "Page “{p}” · space {n}",
    "Novo: ": "New: ",
    "O que o botão faz?": "What does the button do?",
    "Cancelar": "Cancel",
    "← Outros tipos": "← Other types",
    "Escolha o app": "Choose the app",
    "Qual site?": "Which site?",
    "Salvar": "Save",
    "Adicionar": "Add",
    "ex.: cmd+shift+4": "e.g. cmd+shift+4",
    "ex.: ctrl+c": "e.g. ctrl+c",
    "Aperte o atalho": "Press the shortcut",
    "Ou escreva": "Or type it",
    "Atalhos que o navegador não deixa gravar (como {k}) podem ser escritos à mão.": "Shortcuts the browser won't let you record (like {k}) can be typed by hand.",
    "ex.: Já te respondo!": "e.g. Be right back!",
    "O que digitar": "What to type",
    "Usar ": "Use ",
    "Feito no config.json": "Made in config.json",
    "← Cancelar troca": "← Cancel change",
    "Tipo do botão": "Button type",
    "Outro (config.json)": "Other (config.json)",
    "Nome no botão": "Name on the button",
    "Pedir um segundo toque antes de executar": "Ask for a second tap before running",
    "Mover para outra página": "Move to another page",
    "Mover para…": "Move to…",
    "Remover botão": "Remove button",
    "Abrir em": "Open in",
    "Navegador padrão": "Default browser",
    " (não achei aqui)": " (not found here)",
    "Endereço": "Address",
    "Se a aba já estiver aberta, só trazer para frente": "If the tab is already open, just bring it to the front",
    "Sequência de {n} atalhos: {s}. Grave um novo para trocar.": "Sequence of {n} shortcuts: {s}. Record a new one to replace it.",
    "Ação": "Action",
    "Volume em %": "Volume in %",
    "Definir": "Set",
    "Volume (%)": "Volume (%)",
    "Liga e desliga o mudo do microfone do computador. No celular, a luz MUDO acende enquanto ele estiver mudo.": "Mutes and unmutes the computer's microphone. On the phone, the MUTE light stays on while it's muted.",
    "O computador dorme na hora. Para acordar: qualquer tecla ou o mouse. No Mac com \"Despertar para acesso à rede\" ligado e um Apple TV, HomePod ou roteador Apple na rede, ele acorda sozinho quando o Deck abre no celular.": "The computer sleeps right away. To wake it: any key or the mouse. On a Mac with \"Wake for network access\" on and an Apple TV, HomePod or Apple router on the network, it wakes by itself when Deck opens on the phone.",
    "Vai para a tela de bloqueio; os programas continuam abertos.": "Goes to the lock screen; programs stay open.",
    "Fecha tudo e liga de novo. Programas com trabalho não salvo podem segurar o reinício.": "Closes everything and starts again. Programs with unsaved work may hold up the restart.",
    "Desliga de verdade. O celular não consegue ligar um computador desligado (não há nada rodando para receber o pedido) — se quiser ligar de longe, prefira Suspender.": "Really shuts down. The phone can't turn on a computer that's off (nothing is running to receive the request) — to wake it remotely, prefer Sleep.",
    "Escolha a página": "Choose the page",
    "Ir para": "Go to",
    "Este botão é um ": "This button is a ",
    "tipo especial": "special type",
    " feito direto no config.json. Aqui dá para mudar nome, ícone, cor e lugar; o que ele faz continua igual.": " made directly in config.json. Here you can change its name, icon, color and place; what it does stays the same.",
    "Do computador": "From the computer",
    "Do site": "From the site",
    "Imagem": "Image",
    "Sem ícone": "No icon",
    "Dica: ⌃⌘Espaço abre os emojis do Mac.": "Tip: ⌃⌘Space opens the Mac's emoji picker.",
    "Dica: Win + . abre os emojis.": "Tip: Win + . opens the emoji picker.",
    "Cole um emoji ou escreva até 2 letras.": "Paste an emoji or type up to 2 letters.",
    "Imagem: ": "Image: ",
    " (pasta icones). ": " (icones folder). ",
    "Trocar": "Change",
    "O ícone é o mesmo do app no computador.": "The icon is the same as the app's on the computer.",
    "O ícone é o do próprio site.": "The icon is the site's own.",
    "Imagem grande demais (máximo 4 MB).": "Image too large (4 MB max).",
    "Cor do botão": "Button color",
    "Sem cor": "No color",
    "ex.: youtube.com": "e.g. youtube.com",
    "Procurar ou digitar um endereço…": "Search or type an address…",
    "Sites sugeridos": "Suggested sites",
    "Buscando o ícone do site…": "Fetching the site's icon…",
    "Não consegui abrir o site agora — por enquanto fica a inicial no lugar do ícone.": "Couldn't open the site right now — for now the initial stands in for the icon.",
    "Abas abertas agora": "Tabs open now",
    "Favoritos": "Bookmarks",
    "Mais visitados": "Most visited",
    "Abrir ": "Open ",
    "Procurando abas, favoritos e sites mais visitados…": "Looking for tabs, bookmarks and most visited sites…",
    "Nada com “{q}”. Digite o endereço completo (ex.: nome.com).": "Nothing matching “{q}”. Type the full address (e.g. name.com).",
    "Digite o endereço de um site (ex.: youtube.com).": "Type a site's address (e.g. youtube.com).",
    "Procurar de novo as abas abertas": "Look for open tabs again",
    "Atualizar": "Refresh",
    "Sugestões deste computador": "Suggestions from this computer",
    "Procurar app…": "Search app…",
    "Procurar app": "Search app",
    "Apps deste computador": "Apps on this computer",
    "Procurando os apps deste {s}…": "Looking for the apps on this {s}…",
    "computador": "computer",
    "Usar “{n}” como nome do app": "Use “{n}” as the app name",
    "Não achei apps neste computador.": "Couldn't find apps on this computer.",
    "Gravar atalho: clique e aperte as teclas": "Record shortcut: click and press the keys",
    "Clique aqui e aperte o atalho": "Click here and press the shortcut",
    "Aperte as teclas agora…": "Press the keys now…",
    "“{n}” removido.": "“{n}” removed.",
    "Desfazer": "Undo",
    "A página “{p}” está cheia. Libere um espaço ou mude a grade.": "Page “{p}” is full. Free a space or change the grid.",
    "Movido para “{p}”.": "Moved to “{p}”.",
    "Página “{p}” apagada.": "Page “{p}” deleted.",
    "Crie outra página para poder mover botões.": "Create another page to be able to move buttons.",
    "Esta página está cheia. Libere um espaço ou aumente a grade nas configurações.": "This page is full. Free a space or enlarge the grid in the settings.",
    "Link novo gerado. Escaneie o QR code de novo nos celulares.": "New link generated. Scan the QR code again on the phones.",
    "Celular desconectado": "Phone disconnected",
    "Conectar celular": "Connect phone",
    "O config.json mudou fora do editor — atualizei aqui.": "config.json changed outside the editor — updated here.",
    "Como usar": "How to use",
    "Nova página": "New page",
    "O editor só abre no próprio computador onde o deck está ligado: ": "The editor only opens on the computer where the deck is running: ",
    "Não consegui falar com o deck. Ele está ligado? Tentando de novo…": "Couldn't reach the deck. Is it on? Trying again…",
    "Nome do deck": "Deck name",
    "Mais produtividade,<br>todos os dias.": "More productivity,<br>every day.",
    "Páginas": "Pages",
    "Adicionar botão": "Add button",
    "Adicionar um app": "Add an app",
    "Adicionar um site": "Add a site",
    "Procurar botão": "Find button",
    "Procurar": "Find",
    "Editar esta página": "Edit this page",
    "Editar página": "Edit page",
    "Procurar botão em todas as páginas…": "Find a button on all pages…",
    "Carregando…": "Loading…",
    "Páginas (como no celular)": "Pages (as on the phone)",
    "Editar": "Edit",
    "Fechar": "Close",
    "Mover para outra página…": "Move to another page…",
    "Remover": "Remove",
    "Posição": "Position",
    "Tocar ou pausar": "Play or pause",
    "Volume": "Volume",
    "Nada tocando agora": "Nothing playing right now",
    "Dê play no Spotify, no YouTube ou em qualquer player do computador — aparece aqui.": "Press play on Spotify, YouTube or any player on the computer — it shows up here.",
    "Sem título": "Untitled",
    "Pausar": "Pause",
    "Tocar": "Play",
    "Tocando agora: {t}": "Now playing: {t}",
    "{t}: tempo encerrado": "{t}: time's up",
    "Retomar": "Resume",
    "Encerrar": "End",
    "Fim": "Done",
    "Chamada": "Call",
    "Chamada chegando no computador": "Incoming call on the computer",
    "Atendendo no computador…": "Answering on the computer…",
    "Chamada recusada.": "Call declined.",
    "Modo": "Mode",
    "Foco, trabalho, estudo: abre, fecha e silencia": "Focus, work, study: opens, closes and silences",
    "Atender, mudo, câmera, encerrar": "Answer, mute, camera, hang up",
    "Atender": "Answer",
    "Recusar": "Decline",
    "Câmera": "Camera",
    "Um toque deixa o computador do jeito certo para cada momento.": "One tap sets the computer up just right for each moment.",
    "Atender, mutar e sair das chamadas sem procurar a janela.": "Answer, mute and leave calls without hunting for the window.",
    "Player (modo DJ): mostra o que está tocando no computador, com capa e controles.": "Player (DJ mode): shows what's playing on the computer, with artwork and controls.",
    "No celular, esta página vira um player em tela cheia com capa, tempo, pular, voltar e volume. Ela aparece quando você desliza até ela ou toca no mini player do canto.": "On the phone, this page becomes a full-screen player with artwork, time, skip, back and volume. It shows up when you swipe to it or tap the mini player in the corner.",
    "Dê play em qualquer player do computador para ver aqui.": "Press play in any player on the computer to see it here.",
    "Botões": "Buttons",
    "Player (modo DJ)": "Player (DJ mode)",
    "Esta é a página {p} de {t}": "This is page {p} of {t}",
    "Tipo da página": "Page type",
    "O player mostra o que está tocando no computador (Spotify, YouTube, Apple Music…). Os botões que a página tinha ficam guardados se você voltar para Botões.": "The player shows what's playing on the computer (Spotify, YouTube, Apple Music…). The page's buttons are kept in case you switch back to Buttons.",
    "Player (modo DJ) troca os botões por um mini player do que estiver tocando no computador.": "Player (DJ mode) swaps the buttons for a player of whatever is playing on the computer.",
    "Foco": "Focus",
    "Mudo na chamada": "Mute call",
    "Tirar {i}": "Remove {i}",
    "No Mac, o deck liga o Foco pelo app Atalhos: crie uma vez os atalhos “Deck Foco Ligar” e “Deck Foco Desligar” com a ação “Definir Foco” (Não Perturbe › Ligado/Desligado).": "On a Mac, the deck turns on Focus through the Shortcuts app: create the shortcuts “Deck Focus On” and “Deck Focus Off” once, with the “Set Focus” action (Do Not Disturb › On/Off).",
    "No Windows não há como ligar o Não perturbe por programa: o deck avisa no celular para você ligar em Win+N.": "Windows doesn't let programs turn on Do Not Disturb: the deck reminds you on the phone to turn it on with Win+N.",
    "No Linux funciona no GNOME (esconde os avisos na tela).": "On Linux it works on GNOME (hides on-screen notifications).",
    "Não mexer": "Leave as is",
    "Ativar": "Turn on",
    "Desativar": "Turn off",
    "Sem": "None",
    "Minutos": "Minutes",
    "Outro": "Other",
    "Volume do modo": "Mode volume",
    "Ajustar": "Set",
    "Ir para a página": "Go to page",
    "Ficar na página atual": "Stay on the current page",
    "Um toque liga o modo; outro toque desliga (e desfaz o Não perturbe). Só um modo fica ligado por vez.": "One tap turns the mode on; another tap turns it off (and undoes Do Not Disturb). Only one mode is on at a time.",
    "Não perturbe": "Do Not Disturb",
    "Cronômetro na tela do celular": "Timer on the phone screen",
    "minutos": "minutes",
    "Abrir": "Open",
    "App ou site (ex.: Notion, gmail.com)": "App or site (e.g. Notion, gmail.com)",
    "Fechar apps que distraem": "Close distracting apps",
    "Nome do app (ex.: WhatsApp)": "App name (e.g. WhatsApp)",
    "Depois, no celular": "Then, on the phone",
    "App da chamada": "Call app",
    "O deck traz o app para frente e aperta o atalho de atender dele (Zoom, Teams e Discord têm).": "The deck brings the app to the front and presses its answer shortcut (Zoom, Teams and Discord have one).",
    "Sem chamada aberta, este botão silencia o microfone do computador.": "With no call open, this button mutes the computer's microphone.",
    "No Zoom, sair pede confirmação na tela.": "In Zoom, leaving asks for confirmation on screen.",
    "No Meet, encerrar fecha a aba da reunião.": "In Meet, hanging up closes the meeting tab.",
    "A página “{p}” é o player (modo DJ) e não tem botões.": "The page “{p}” is the player (DJ mode) and has no buttons.",
    "Esta página é o player (modo DJ). Para pôr botões, mude o tipo da página.": "This page is the player (DJ mode). To add buttons, change the page type.",
    "+5 min": "+5 min",
    "Minimizar": "Minimize",
    "Mostrar o cronômetro de {t}": "Show the {t} timer",
    "{p} (não existe mais)": "{p} (no longer exists)",
    "Arraste para mudar a ordem · clique duas vezes para renomear": "Drag to reorder · double-click to rename",
    "Arraste para mudar a ordem": "Drag to reorder",
    "“{p}” agora é a página {n}.": "“{p}” is now page {n}.",
    "Descer": "Down",
    "Ordem": "Order",
    "Ou arraste a página na lateral (ou na barra de páginas) para o lugar que quiser. No celular, a ordem muda junto.": "Or drag the page in the sidebar (or in the page bar) to wherever you want. The phone follows the new order.",
    "Automático (a chamada que estiver na frente)": "Automatic (the call in front)",
    "No automático, o deck usa o app de chamada que estiver na frente no computador (WhatsApp, Zoom, Teams, Meet…); se nenhum estiver, a reunião aberta.": "In automatic, the deck uses the call app that is in front on the computer (WhatsApp, Zoom, Teams, Meet…); if none is, the open meeting.",
    "No WhatsApp, use durante a chamada: fora dela, o mesmo atalho silencia a conversa aberta.": "In WhatsApp, use it during the call: outside a call, the same shortcut mutes the open chat.",
    "O WhatsApp não tem atalho de atender: no Mac, a ligação aparece no celular com Atender e Recusar.": "WhatsApp has no answer shortcut: on a Mac, the call shows up on the phone with Answer and Decline.",
    "No Mac, ligações do FaceTime, do iPhone (pela Continuidade) e do WhatsApp aparecem no celular com Atender e Recusar. Nos outros apps, o deck usa o atalho do app.": "On a Mac, FaceTime, iPhone (via Continuity) and WhatsApp calls show up on the phone with Answer and Decline. In other apps, the deck uses the app's shortcut.",
    "Oculta no celular · arraste para mudar a ordem": "Hidden on the phone · drag to reorder",
    "Mostrar “{p}” no celular": "Show “{p}” on the phone",
    "Ocultar “{p}” do celular": "Hide “{p}” from the phone",
    "“{p}” voltou para o celular.": "“{p}” is back on the phone.",
    "“{p}” não aparece mais no celular. Continua aqui no editor.": "“{p}” no longer shows on the phone. It stays here in the editor.",
    "Todas as páginas estão ocultas: o celular fica vazio.": "All pages are hidden: the phone will be empty.",
    "No celular": "On the phone",
    "Mostrar esta página no celular": "Show this page on the phone",
    "Oculta: o celular pula esta página, mas ela continua aqui no editor com os botões.": "Hidden: the phone skips this page, but it stays here in the editor with its buttons.",
    "Desligue para esconder a página do celular sem apagar. Também dá pelo olho ao lado do nome, na lateral.": "Turn off to hide the page from the phone without deleting it. You can also use the eye next to its name in the sidebar.",
    "Oculta no celular": "Hidden on the phone",
    "Essa página está oculta no celular.": "That page is hidden on the phone.",
    "Todas as páginas estão ocultas": "All pages are hidden",
    "No editor do computador, clique no olho ao lado de uma página para ela voltar a aparecer aqui.": "In the editor on the computer, click the eye next to a page to bring it back here.",
  };
  var raiz = document.documentElement;
  var idioma = /^en/i.test(raiz.getAttribute('lang') || '') ? 'en' : 'pt';
  var tem = Object.prototype.hasOwnProperty;
  function tr(texto, vars) {
    var r = idioma === 'en' && tem.call(EN, texto) ? EN[texto] : texto;
    if (vars) Object.keys(vars).forEach(function (k) { r = r.split('{' + k + '}').join(String(vars[k])); });
    return r;
  }
  function traduzirPagina(base) {
    base = base || document;
    var marcados = base.querySelectorAll('[data-t]');
    for (var i = 0; i < marcados.length; i++) {
      var el = marcados[i];
      if (el.children.length) {
        var html = el.innerHTML.trim();
        if (idioma === 'en' && tem.call(EN, html)) el.innerHTML = EN[html];
      } else {
        el.textContent = tr(el.textContent.trim());
      }
    }
    if (idioma !== 'en') return;
    ['title', 'placeholder', 'aria-label', 'alt'].forEach(function (atributo) {
      var lista = base.querySelectorAll('[' + atributo + ']');
      for (var j = 0; j < lista.length; j++) {
        var v = lista[j].getAttribute(atributo);
        if (tem.call(EN, v)) lista[j].setAttribute(atributo, EN[v]);
      }
    });
  }
  window.tr = tr;
  window.IDIOMA = idioma;
  window.traduzirPagina = traduzirPagina;
  traduzirPagina();
})();
